### ISSUE TITLE
Patch for /README.md

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damonkohler/android-scripting#703]
```
G
```

Original issue reported on code.google.com by `HenryCon...@googlemail.com` on 14 Jan 2014 at 11:26

Attachments:
* [README.md.patch](https://storage.googleapis.com/google-code-attachments/android-scripting/issue-703/comment-0/README.md.patch)

**Comment by damonkohler** [comment]
This issue was moved to damonkohler/sl4a#15
